# DO NOT TOUCH #
Version: 2.8.7
################

############################################################
# +------------------------------------------------------+ #
# |                    PLUGIN CONTROL                    | #
# +------------------------------------------------------+ #
############################################################

# Customizable plugin prefix.
PluginPrefix: "&f[&6PvPTitles&f] "

# Enable/Disable metrics.
Metrics: true

# Notice Update Available.
Alert: true
# Automatic updates.
Update: false

# Display integrations
DisplayIntegrations: true

# Debug mode (Shows database queries in console)
Debug: false

# Error structure:
# 0 - Simplified.
# 1 - Essential data.
# 2 - All data.
ErrorFormat: 2

# Options (No case sensitive):
# - SQLite
DefaultDatabase: SQLite

############################################################
# +------------------------------------------------------+ #
# |                 MYSQL-PVPTITLES BRIDGE               | #
# +------------------------------------------------------+ #
############################################################

# False to work with SQLite.
# True to hook {connect} into the existing server MySQL.
Mysql:
    enable: false       
    enableSSL: false
    
    host: localhost
    port: 3306
    database: dbname
    user: user
    pass: pass
  
# Unique ID per server (Default -1 indicates that the server has not ID)
MultiS: -1
# Custom name for this server (If empty server name will be used)
NameS: Custom

############################################################
# +------------------------------------------------------+ #
# |                      MULTIWORLD                      | #
# +------------------------------------------------------+ #
############################################################

# MultiWorld
MW:
    # Enable points per world
    enable: false
        
# Manage some plugin features between worlds.
MW-filter:
    # It shows the titles on the worlds listed below.
    title: false
    # Awards points for fame on the worlds listed below.
    points: false
    # It shows the players, who played in the worlds listed below, on the leaderboard (pvpladder and boards)
    show-on-leaderboard: false
    # List of affected worlds (No case sensitive)
    affected-worlds:
    - example_world

############################################################
# +------------------------------------------------------+ #
# |                        EVENTS                        | #
# +------------------------------------------------------+ #
############################################################

# Update Time for leaderboards (IN MINUTES)
LBRefresh: 1

# Task to check if a player got a new Rank (Useful if that rank requires a 
# minimum played time) (IN SECONDS)
RankChecker: 30

# ** You CAN DISABLE the events (if you don't need them) putting in the fields '-1' **

############################################################
# +------------------------------------------------------+ #
# |                         PURGE                        | #
# +------------------------------------------------------+ #
############################################################

# Command Purge. Erase the data older than (In days)
TimeP: 20
# List of players who will not be deleted with the command (Case sensitive)
NoPurge: []

############################################################
# +------------------------------------------------------+ #
# |                        ANTIFARM                      | #
# +------------------------------------------------------+ #
############################################################

## KILLSTREAKS ##
# Maximum number of deaths on the same player during "TimeL"
Kills: 3
# Necessary time to clean the deaths on a player (In seconds)
# It is restarted for each death.
CleanerTime: 200
# Veto time [Stops getting points by law] (in seconds)
VetoTime: 300
# Prevent getting fame from every player or just from abused player?
PreventFromEvery: true

## PLAYED TIME ##
# Enable/Disable checking afk.
CheckAFK: true
# AFK Time (Time to considerer a player as afk, in minutes)
AFKTime: 5

############################################################
# +------------------------------------------------------+ #
# |                      MULTIPLIERS                     | #
# +------------------------------------------------------+ #
############################################################

## MULTIPLIERS ##
#
# Configure custom multipliers to increase or decrease the amount of <reward>
# that a player receives. By default, the multiplier is 1. (Nothing changes)
#
# You can use a decimal value, greater than zero, to define the multiplier.
# The result of the operation will be rounded. 
#
# Available multipliers: 
# -> Rewards (Configured in rewards.yml)
#    -> RMoney (Use "money" keyword inside of the reward)
#    -> RPoints (Use "points" keyword inside of the reward)
#    -> RTime (Use "time" keyword inside of the reward)
# -> Defaults (General)
#    -> Points (Per kill)
#    -> Time (Played time)
#
# ---
# Permission format: pvptitles.mp.<reward_name>.<custom_name>
# ---
# In addition, there are some keywords to group the multipliers:
# - pvptitles.mp.*.<custom_name> (ALL)
# - pvptitles.mp.rewards.<custom_name> (RMoney, RPoints, RTime)
# - pvptitles.mp.defaults.<custom_name> (Points and Time)
#
# For example, the permission for this example
# Multipliers:
#     RMoney:
#         vip: 1.25
# is -> pvptitles.mp.rmoney.vip
Multipliers:
    RMoney:
        vip: 1.25
    RPoints:
        vip: 1.25
    RTime:
        vip: 1.25
    Points:           
        vip: 1.5
    Time:
        vip: 2

############################################################
# +------------------------------------------------------+ #
# |                         POINTS                       | #
# +------------------------------------------------------+ #
############################################################

## KILLSTREAK/DEATHSTREAK ##
# Reset killstreak when a player be killed by:
# AVAILABLE OPTIONS:
# - PLAYER -> Another player.
# - ENVIRONMENT -> Everything else.
# If empty it won't be reset.
ResetOptions:
- PLAYER
# Add a death to deathstreak only when it is caused by a player.
AddDeathOnlyByPlayer: true
# Should be reset the killstreak/deathstreak value when a player leaves the server?
ResetOnPlayerLeaving: true
# Remember that killstreak/deathstreak are temporary values, these will be zero 
# when server restarts.

## AWARDED POINTS ##
# RP -> Receive Points.
# LP -> Lose Points.
RPWhenKilling: 
    # Enable to Receive Points when killing.
    enable: true
LPWhenDying: 
    # Enable to Lose Points when dying.
    enable: false
    # Only by other players?
    onlyPlayers: false

## MODIFICATOR ##
# Modificator to increase or decrease the amount of points you receive/lose.
# The result will be parsed to integer.
#
# Available variables (No case sensitive): 
# - STREAK -> KillStreak or "DeathStreak"
# - MOD -> Modificator value.
# - KPOINTS -> Killer points.
# - VPOINTS -> Victim points.
#
# Allowed functions (Parameters between parentheses):
# - https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html
#     -> Just use the name of the functions described into "Method Summary" 
#     -> By default, the parameters type is "double"
Modificator:
    # When you are the killer.
    Received:
        # Formula to calculate the points.
        formula: "ceil(((STREAK - 1) * MOD) + 1)"
        # Modificator value.
        value: 0.5
    # When you are the victim.
    Lost:
        formula: "STREAK"
        value: 0
# Default formula: (Killstreak * mod) + 1 | (Result is truncated upward)
#   - Example: [Second low # (1 * 0.25 + 1) = 1.25 ~ 2 #
#   - Recommended value between 0 - 1

############################################################
# +------------------------------------------------------+ #
# |                     CHAT & TITLES                    | #
# +------------------------------------------------------+ #
############################################################

# Default translations (Spanish (ES) | English (EN))
# ############################# // Custom translations available \\ ##############################
# German (DE) | Greek (GR) | French (FR) | Japanese (JP) | Chinese (CH) | Simplified Chinese (CN)
# Russian (RU) | Portuguese (PT) | Swedish (SV) | Czech (CS) | Euskara (EU) | Galician (GL)
# Catalan (CA) | Croatian (HR) | Korean (KO) | Ukrainian (UK) | Polish (PL) | Slovenian (SL)
# Serbian (SR) | Romanian (RO)
# ################################################################################################
DefaultLang: EN
## For system messages and for players whose launcher has another language ##
## [Custom translations] Also, you can add your own translations...
## Example: You can create "messages_DE" and the messages into the file will be shown to the players whose launcher language is German.

# Customizable Name for the points earned by players.
Tag: Fame

# Number of the top players that will be shown in chat with the pvpladder command.
Top: 5

# Format for all ranks, colors on display option have more priority than these ones.
# "%T" will be replaced by the display of the rank
RanksFormat: "&6%T&r"

# Prefix in the chat to replace.
Prefix: "{PVPTITLE}"
# If you do not use any chat-plugin or do not want to implement it the title will be placed at the beginning of chat.

# Display the player title in the chat.
DisplayTitleInChat: true

## HOLOGRAMS ##
# Display the player title over his head.
DisplayTitleOverPlayer: false
# Holographic title's format (For all ranks) [Supports colors]
HoloTitleFormat: "[%rank%]"
# Modifier for setting the hologram height (Min value = 0)
# -> GRAPHIC EXAMPLE <-
# ---    (...)   --- (n)
# ---            --- (2)
# ---            --- (1) [Default height]
# --- playername --- (0) [This coincides with the height of player name]
# --- ( player ) ---
HoloHeightModifier: 1
# This requires that HolographicDisplays be loaded.
## -- ##

## RANKS/TITLES ##
#
# Default rank "None" won't be shown.
# If display is not defined, the rank name will be used.
#
# Structure explanation:
# <title_name>: (Has to be unique)
#     display: "&bTitle &ename" (Name to display)
#     points: <points_number> (Points required to get the title)
#     # OPTIONAL PARAMETERS
#     # time: <seconds> (Required played time (In seconds) to get the title, 0 by default)
#     # restricted: true|false (Requires a permission to get the title, false by default)     
#
# If you use "restricted: true", the permission that you have to use is:
#     pvptitles.rank.<title_name>
Ranks:
    None:
        points: 0
    Hero: 
        display: "&aHero&r"
        points: 25
    Fierce_Hero: 
        display: Fierce Hero
        points: 75
    Mighty_Hero: 
        display: Mighty Hero
        points: 180
    Deadly_Hero: 
        display: Deadly Hero
        points: 360
    Terrifying_Hero: 
        display: Terrifying Hero
        points: 600
    Conquering_Hero: 
        display: Conquering Hero
        points: 1000
    Subjugating_Hero: 
        display: Subjugating Hero
        points: 1680
    Vanquishing_Hero: 
        display: Vanquishing Hero
        points: 2800
    Renowned_Hero: 
        display: Renowned Hero
        points: 4665
    Illustrious_Hero: 
        display: Illustrious Hero
        points: 7750
    Eminent_Hero: 
        display: Eminent Hero
        points: 12960
    Kings_Hero: 
        display: Kings Hero
        points: 21600
    Emperors_Hero: 
        display: Emperors Hero
        points: 36000
    Balthazar_Hero: 
        display: Balthazar Hero
        points: 60000
    Legendary_Hero: 
        display: Legendary Hero
        points: 100000